---
title: "Replication of 'Early Cerebral Constraints on Reading Skills in School-Age Children: An MRI Study' X by Borst et al. (2016, Mind, Brain, & Education)"
author: "Jewelia Yao (jkyao@stanfod.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standsafardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

Borst et al. (2016) examines the relationship between individual morphological differences in the occipital temporal temporal sulcus (OTS), a sulcus in ventral temporal cortex of the brain, and reading skills in school-aged children. Using anatomical magnetic resonance imaging scans from 16 children, this study classified the OTS in both the right and left hemispheres as either interrupted or continuous based on microgyral breaks in the sulcus. Using multiple linear regressions, they related this binary categorization to oral reading scores on the Alouette-R test and found that children whose left OTS had an interruption performed better than children whose left OTS were continuous. This finding suggests that reading skills can be constrained anatomical features of cerebral cortex. 

### Justification

Understanding the neuroanatomical underpinnings of the development of brain function and behavior has been a major interest of developmental neuroscience. Sulci are  features that a) have been shown to act as landmarks or boundaries for functional regions in the brain and b) have individual variabilities that are related to aspects of cognition. As characterizing sulci on an individual level is manual and laborious work, previous studies has often analyzed brain structure using group averages, which wash out individual variability in sulcal patterns. Borst et al. (2016) examines sulci on the individual level and relates it to behavior. This result has been of particular interest to me because I am generally interested in the coupling of brain structure, function, and behaviors related to educational development, and specifically, my upcoming work will examine reading development in kids with/without dyslexia and how it relates to aspects of visual cortex (such as sulcal morphology). My previous work has mostly been in prefrontal cortex, so this would be a great opportunity to explore visual cortex anatomy and its relationship to reading.

### Procedures & Anticipated Challenges

Procedures: Using pre-collected anatomical MRI data from the Grill-Spector Lab and Yeatman Lab, I will manually define and the OTS and the left and right hemispheres of 16 children in Freesurfer, a brain imgaing tool program. I If time permits, I will label an additional 44 subjects to meet the Developmental Cognitive Neuroscience Journal threshold of N=60. Given my previous experience with labeling sulci and the individual variability, the manual labeling of each hemisphere should take approximately 10 minutes (10min x 2 hemispheres x 16-60 subjects = ~5-20hrs). I will then classify each sulcus as interrupted or continuous based on criteria in Borst et al. (2016). These labels will be confirmed for accuracy by an expert anatomist(s). Following this data processing, I will use multiple regression (as done in the study) to relate OTS breakage to reading scores on the Test of Word Reading Efficiency (TOWRE), which is similar to the Alouette-R in that it is an oral, timed reading task. TOWRE is in English, but Alouette is in French and not applicable to this sample.

Anticipated Challenges: Manually labeling and characterizing sulcal anatomy is time intensive and detailed work requiring an understanding of the neighboring sulcal anatomy and precise judgement given cases of extreme variability in sulcal patterning. This will be challenging as I have never worked in this brain region before and because there will likely be cases in which the OTS is harder to idenfity or determine cutoffs. Additionally, navigating brain data also requires manually checking scans for artifacts and preprocessing the raw data which will add time. However, I have both collected and preprocessed neural data before and do not expect this to be a huge setback.

### Links

Project repository (on Github): https://github.com/psych251/borst2016.git

Original paper (as hosted in your repo): https://github.com/psych251/borst2016/blob/master/original_paper/Borst_etal_2016_MindBrainEducation.pdf


##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
