---
title: "Replication of 'Early Cerebral Constraints on Reading Skills in School-Age Children: An MRI Study' by Borst et al. (2016, Mind, Brain, & Education)"
author: "Jewelia Yao (jkyao@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---


## Introduction

Borst et al. (2016) examines the relationship between individual morphological differences in the occipital temporal temporal sulcus (OTS), a sulcus in ventral temporal cortex of the brain, and reading skills in school-aged children. Using anatomical magnetic resonance imaging scans from 16 children, this study classified the OTS in both the right and left hemispheres as either interrupted or continuous based on microgyral breaks in the sulcus. Using multiple linear regressions, they related this binary categorization to oral reading scores on the Alouette-R test and found that children whose left OTS had an interruption performed better than children whose left OTS were continuous. This finding suggests that reading skills can be constrained anatomical features of cerebral cortex. 

### Justification

Understanding the neuroanatomical underpinnings of the development of brain function and behavior has been a major interest of developmental neuroscience. Sulci are features that a) have been shown to act as landmarks or boundaries for functional regions in the brain and b) have individual variabilities that are related to aspects of cognition. As characterizing sulci on an individual level is manual and laborious work, previous studies has often analyzed brain structure using group averages, which wash out individual variability in sulcal patterns. Borst et al. (2016) examines sulci on the individual level and relates it to behavior. This result has been of particular interest to me because I am generally interested in the coupling of brain structure, function, and behaviors related to educational development, and specifically, my upcoming work will examine reading development in kids with/without dyslexia and how it relates to aspects of visual cortex (such as sulcal morphology). My previous work has mostly been in prefrontal cortex, so this would be a great opportunity to explore visual cortex anatomy and its relationship to reading.

### Anticipated Challenges

Manually labeling and characterizing sulcal anatomy is time intensive and detailed work requiring an understanding of the neighboring sulcal anatomy and precise judgement given cases of extreme variability in sulcal patterning. This will be challenging as I have never worked in this brain region before and because there will likely be cases in which the OTS is harder to idenfity or determine cutoffs. Additionally, navigating brain data also requires manually checking scans for artifacts and preprocessing the raw data which will add time. However, I have both collected and preprocessed neural data before and do not expect this to be a huge setback.

### Links

Project repository: https://github.com/psych251/borst2016.git

Original paper: https://github.com/psych251/borst2016/blob/master/original_paper/Borst_etal_2016_MindBrainEducation.pdf


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Using pre-collected anatomical MRI data from the Yeatman Lab akin to data used in Borst et al. (2016), I will manually define the OTS in the left and right hemispheres of 16 typically developing, right-handed children (8 females) between the ages of 9 and 11. If time permits, I will label an additional 44 subjects to meet the Developmental Cognitive Neuroscience Journal threshold of N=60.

### Materials

**Reading Test**
Children’s reading proficiency will be evaluated with the Test of Word Reading Efficiency(TOWRE)test, which is a standardized test for assessing oral reading in English. Participants are instructed to read off words orally as fast as possible while maintaining correct pronunciation. The test is time-limited (45 seconds). In the present study, we focused on reading accuracy, which was reflected by the number of words that were correctly read in 45sec. Children were tested after completing the MRI.

**MRI Data Preparation and Acquisition**
Pre-acquired three-dimensional (3D) T1-weighted spoiled gradient images using a 3T MRI scanner (GE Discovery Scanner, Stanford University). Image analysis was performed with FreeSurfer (https://surfer.nmr.mgh.harvard.edu), version 6.0. An automated pre-processing step was used to skull-strip the T1 MRIs. Volumes were segmented to grey and white matter to produce a reconstruction of the cortical surface as well as a definition of the cortical ribbon. Images at each processing step for each MRI were visually checked and no motion artifacts or segmentation errors were observed.

### Procedure	
Using pre-collected anatomical MRI data, I will process and manually check image quality of T1-weighted anatomical scans in FreeSurfer (https://surfer.nmr.mgh.harvard.edu), a brain imaging program. Given previous experience with labeling sulci and the individual variability, the manual labeling of each hemisphere should take approximately 10 minutes (10min x 2 hemispheres x 16-60 subjects = ~5-20hrs). In FreeSurfer, I will then classify the OTS in the left and right hemisphere of each child (N=16) as interrupted or continuous based on criteria in Borst et al. (2016) which characterizes interruptions in the OTS as ones with gaps that were larger than 20mm. These labels will be confirmed for accuracy by an expert anatomist(s). Following this data processing, I will use multiple linear regressions to relate OTS breakage to reading scores on the Test of Word Reading Efficiency (TOWRE), which is similar to the Alouette-R in that it is an oral, timed reading task. 

### Analysis Plan

**Reading Statistics & Correlations**

Get average number and standard deviation of words correctly read on the reading test. Correlate age and number of correctly read words.

**Multiple Linear Regressions** 

Model 1: the number of words correctly read as the outcome variable and (a) the sulcal pattern of the lateral OTS in the left hemisphere, (b) the sulcal pattern of the lateral OTS in the right hemisphere, and (c) age in months as predictor variables

Model 2: the number of words correctly read as the outcome variable and age in months as a predictor variable

Model 3: the number of words correctly read as the outcome variable and (a) the sulcal pattern of the lateral OTS in the left hemisphere and (b) the sulcal pattern of the lateral OTS in the right hemisphere as predictor variables


### Differences from Original Study

Data will not be collected from the same 3T scanner or with the exact same parameters. As T1 images/anatomical scans are typically consistent across 3T scanner, there should not be great scan variation between the quality of anatomical scans from the original study and the present replication.

The sample will also be an English-speaking one, rather than French, so the oral reading test will also be an English test (TOWRE) equivalent to the Alouette-R. There should not be great differences, as the tests are administered similarly and test for the same things ;additionally, most reading tests are highly correlated with one another. TOWRE is in English, but the Alouette-R test is in French and not applicable to this sample.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
